t = Todo.create(title:"run1",body:"running in SF",done:false)
Step.create(todo_id: t.id, body:"put on clothes",done:false)
Step.create(todo_id: t.id, body:"shoes",done:false)
Todo.create(title:"run2",body:"running in SF",done:false)
Todo.create(title:"run3",body:"running in SF",done:false)
Todo.create(title:"run4",body:"running in SF",done:false)
